version: '3.8'
services:
  app:
    build: .
    image: aashisharyal/sit737week5
    ports:
      - '3043:3050'
    environment:
      - PORT=3043
    container_name: my-app1
    networks:
      - my-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3050/add?n1=5&n2=10"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  app1:
    build: .
    image: aashisharyal/sit737week5
    ports:
      - '3044:3050'
    environment:
      - PORT=3044
    container_name: my-app2
    networks:
      - my-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3050/multiply?n1=5&n2=10"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always


networks:
  my-net:
    driver: bridge